### ISSUE TITLE
SQLiteOnWeb started on http://0.0.0.0:9000 but not browse in mozalla

### ISSUE THREAD

**Issue by guardianlaw** [skyhacker2/SQLiteOnWeb-Android#1]
SQLiteOnWeb started on http://0.0.0.0:9000 but not browse in mozalla

**Comment by skyhacker2** [comment]
@guardianlaw Phone and computer must connect to same wifi.

**Comment by guardianlaw** [comment]
internet is connected through 3g phone to pc via phone hotspot.

**Comment by guardianlaw** [comment]
and phone is connected via adb android studio 1.5

**Comment by jp1017** [comment]
手机电脑必须连同一个 wifi?

**Comment by skyhacker2** [comment]
呃呃，是啊=。=

原始邮件
发件人:蒋朋notifications@github.com
收件人:skyhacker2/SQLiteOnWeb-AndroidSQLiteOnWeb-Android@noreply.github.com
抄送:Eleven Chenskyhacker@126.com; State changestate_change@noreply.github.com
发送时间:2016年11月10日(周四) 18:21
主题:Re: [skyhacker2/SQLiteOnWeb-Android] SQLiteOnWeb started onhttp://0.0.0.0:9000 but not browse in mozalla (#1)

手机电脑必须连同一个 wifi?

**Comment by saket** [comment]
+1 I'm also seeing this problem with my emulator.

**Comment by skyhacker2** [comment]
@Saketme Yes, it don't support emulator now.
