### ISSUE TITLE
因系统限制，看不到W以上级别的 log, 因此看不到地址了，，

### ISSUE THREAD

**Issue by jp1017** [skyhacker2/SQLiteOnWeb-Android#2]
多么悲剧啊，引入你的库？好蛋疼，，　:cry:

**Comment by skyhacker2** [comment]
别这样，怎么蛋疼了呢？😭

原始邮件
发件人:蒋朋notifications@github.com
收件人:skyhacker2/SQLiteOnWeb-AndroidSQLiteOnWeb-Android@noreply.github.com
发送时间:2016年11月10日(周四) 18:22
主题:[skyhacker2/SQLiteOnWeb-Android] 因系统限制，看不到W以上级别的 log, 因此看不到地址了，， (#2)

多么悲剧啊，引入你的库？好蛋疼，，　😢

**Comment by jp1017** [comment]
我的意思是不能 compile 了, 而是把你的当做一个 module, 然后修改输出log级别为 w :sob: 

@skyhacker2

**Comment by skyhacker2** [comment]
@jp1017你能看到你手机的ip吧？手机的ip加上9000端口。

**Comment by skyhacker2** [comment]
@jp1017 欢迎修改后pull request。😝

**Comment by jp1017** [comment]
厉害了
