### ISSUE TITLE
Please connect wifi first

### ISSUE THREAD

**Issue by haofei91** [skyhacker2/SQLiteOnWeb-Android#3]
I have connected Wifi， but  I alse get this error

More, I can not open http://192.168.1.104:9000

**Comment by skyhacker2** [comment]
PC and Phone must in the same local area network

**Comment by lwh912** [comment]
gradle error : Failed to resolve: io.github.skyhacker2:sqliteonweb:1.0.1

**Comment by lwh912** [comment]
can you show a gradle example to me ?

**Comment by skyhacker2** [comment]
@lwh912 Which `compileSdkVersion` do you use?
