### ISSUE TITLE
If a piece of data in a value is null, the entire data key position display is wrong

### ISSUE THREAD

**Issue by szhua** [skyhacker2/SQLiteOnWeb-Android#4]
If a piece of data in a value is null, the entire data key position display is wrong

**Comment by xxxifan** [comment]
same here.
Edit: try use ```debugCompile 'io.github.skyhacker2:sqliteonweb:1.0.2'``` instead of 1.0.1, the latest commit has fix this issue and version bump to 1.0.2 but the author just forget to update it

**Comment by skyhacker2** [comment]
@xxxifan Thanks.
