### ISSUE TITLE
Webpage responseiveness

### ISSUE THREAD

**Issue by MMooreGitHub** [skyhacker2/SQLiteOnWeb-Android#5]
Nice tool!
Can you make the web page responsive?

**Comment by skyhacker2** [comment]
Sorry, I'm not familiar with the front end.

**Comment by MMooreGitHub** [comment]
FYI - throws the following exception after attempting to open a database which uses SQLCipher:
"net.sqlcipher.database.SQLiteException: file is encrypted or is not a database"

**Comment by skyhacker2** [comment]
SQLCipher is unsupported now, may be I will add it later.

**Comment by MMooreGitHub** [comment]
Ok, thanks

**Comment by yuger** [comment]
@skyhacker2 hello 你的google play怎么可以设置头像和背景图片的啊，看起来比较高级，应该怎么弄？

**Comment by skyhacker2** [comment]
@yuger  在google play设置里面的开发者页面可以设置

**Comment by yuger** [comment]
@skyhacker2 找到啦，搜索了很久没有结果，我还以为是企业号呢！ https://support.google.com/googleplay/android-developer/answer/6226441
